---
- name: Install docker
  hosts: all
  become: yes
  vars_files:
    - config.yml

  tasks:
  - name: Install docker and docker-compose
    apt:
      name:
      - docker
      - docker.io
      - docker-compose
      state: present
      update_cache: yes
  - name: post-installation steps
    user:
      name: "{{ vm_user }}"
      groups: docker
      append: yes