---
- name: Install and settings opennebula node
  hosts: all
  become: yes
  vars_files:
    - config.yml
    - "{{ project_dir }}/docker/docker-config.yml" # надо сделать

  tasks:
  - name: Adding opennebula key
    apt_key:
      url: https://downloads.opennebula.io/repo/Ubuntu/repo.key
      state: present
  - name: Adding opennebula repository
    apt_repository:
      repo: deb https://downloads.opennebula.io/repo/6.4/Ubuntu/20.04/ stable opennebula
      state: present
  - name: Install opennebula node
    apt:
      name:
      - opennebula-node
      update_cache: yes

  - name: Copying oneadmin keys from container to virtual_machine
    shell: "docker cp {{ opennebula_container_name }}:/var/lib/one/.ssh/ /var/lib/one/"

  - name: Change permisson for keys
    file:
      path: /var/lib/one/.ssh
      recurse: yes
      owner: oneadmin
      group: oneadmin
      mode: '700'

  # этого тут вроде быть не должно, но что поделать, одна задача
  # Тут мы подключаем ноду vm к opennebula
  - name: Connect opennebula-node (vm) to opennebula front-end
    docker_container_exec:
      container: {{ opennebula_container_name }}
      command: /bin/bash -c "onehost create {{ vm_ip_in_docker_network }} -v kvm -i kvm"